namespace Heirloom.Drawing
{
    /// <summary>
    /// Rich text generated by a <see cref="RichTextParser"/> without the markup and styling information.
    /// </summary>
    public abstract class RichText
    {
        /// <summary>
        /// Gets the plain text component of this <see cref="RichText"/>.
        /// </summary>
        public abstract string Text { get; }

        /// <summary>
        /// Gets the text styling callback.
        /// </summary>
        protected internal abstract DrawTextCallback Callback { get; }
    }
}
